image: node:10.15.3

cache:
  key: "$CI_PIPELINE_ID"
  paths:
    - ./node_modules
    - ./dist

stages:
  - install-dependencies
  - build
  - publish

install-dependencies:
  stage: install-dependencies
  script:
    - npm install

build:
  stage: build
  dependencies:
    - install-dependencies
  script:
    - npm run build
  artifacts:
    name: ${CI_COMMIT_REF_SLUG}
    paths:
    - dist/
    - bin/
    - README.md
    - LICENSE
    - package.json
    - package-lock.json
    - .gitignore
    - .npmignore
    - tsconfig.json

publish:
  stage: publish
  dependencies:
    - build
  only:
    - master
  script:
    - echo '//registry.npmjs.org/:_authToken=${NPM_TOKEN}'>.npmrc
    - npm publish
